---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{include "config-service.fullname" .}}-postgres
  namespace: {{.Values.namespace}}

spec:
  replicas: 1

  selector:
    matchLabels:
      app: {{include "config-service.fullname" .}}-postgres

  template:
    metadata:
      labels:
        app: {{include "config-service.fullname" .}}-postgres

    spec:
      containers:
        - name: postgres
          image: "{{.Values.postgres.image.repository}}:{{.Values.postgres.image.tag}}"

          ports:
            - containerPort: {{.Values.postgres.port}}

          env:
            - name: POSTGRES_DB
              value: "{{.Values.postgres.database}}"

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{include "config-service.fullname" .}}-secret
                  key: DB_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{include "config-service.fullname" .}}-secret
                  key: DB_PASSWORD

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

            - name: db-init-script
              mountPath: /docker-entrypoint-initdb.d

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{include "config-service.fullname" .}}-postgres-pvc

        - name: db-init-script
          configMap:
            name: {{include "config-service.fullname" .}}-db-init