---
apiVersion: v1
kind: Service

metadata:
  name: {{include "config-service.fullname" .}}-postgres
  namespace: {{.Values.namespace}}

spec:
  type: ClusterIP

  selector:
    app: {{include "config-service.fullname" .}}-postgres

  ports:
    - port: {{.Values.postgres.port}}
      targetPort: {{.Values.postgres.port}}