---
apiVersion: v1
kind: Secret

metadata:
  name: {{include "config-service.fullname" .}}-secret
  namespace: {{.Values.namespace}}

type: Opaque

stringData:
  DB_USER: "{{.Values.postgres.username}}"
  DB_PASSWORD: "{{.Values.postgres.password}}"
